name: Dev Branch

on:
  push:
    branches:
      - 'dev'
env:
  LANG: "ru_RU.UTF-8"

jobs:

  test:
    name: Test - Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: ru_RU.UTF-8
        run: |
          sudo locale-gen ru_RU.UTF-8
          sudo update-locale LANG=ru_RU.UTF-8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
        
  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: ru_RU.UTF-8
        run: |
          sudo locale-gen ru_RU.UTF-8
          sudo update-locale LANG=ru_RU.UTF-8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: SonarCloud Scan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
