name: Dev Branch

on:
  push:
    branches:
      - 'dev'

jobs:

  test:
    name: Test - Unit Tests
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Set Locale
        run: java -Duser.language=fr -Duser.country=FR
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
